version: '2'

volumes:
  app-volume:
    external: false
  db-volume:
    external: false

services:

  rproxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql.sra.gx:
    build:
      context: .
      dockerfile: Dockerfile.mymysql
    image: mymysql
    environment:
      - MYSQL_ROOT_PASSWORD=sra1234
      - MYSQL_DATABASE=redmine
    volumes:
      - db-volume:/var/lib/mysql

  redmine.sra.gx:
    image: redmine:3.0.0
    environment:
      - VIRTUAL_HOST=redmine.sra.gx
      - REDMINE_DB_MYSQL=mysql.sra.gx
      - REDMINE_DB_PASSWORD=sra1234
    volumes:
      - app-volume:/usr/src/redmine/files
    depends_on:
      - mysql.sra.gx

# mysql
#   docker-compose exec mysql.sra.gx bash
#   add 'character-set-server=utf8' to /etc/mysql/mysql.conf.d/mysqld.cnf
#   docker-compose restart mysql.sra.gx
# redmine
#   docker-compose exec redmine.sra.gx bash
#   rake db:drop
#   rake db:create
#   rake db:migrate
